# Generated by Django 3.2.6 on 2021-08-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
