# Generated by Django 5.2.1 on 2025-06-02 15:48

import django.db.models.deletion
import system.models
from django.conf import settings
from django.db import migrations, models
from django.db.models import Max


def copy_attachments(attachment_from, attachment_to):
    max_pk = attachment_from.objects.aggregate(pk=Max('pk', default=0))['pk']

    for x in range(1, max_pk + 1):
        try:
            obj_from = attachment_from.objects.get(pk=x)
        except obj_from.DoesNotExist:
            obj_dummy = attachment_to.objects.create(
                file=None,
                md5='',
                author_id=1,
            )
            attachment_to.objects.filter(pk=obj_dummy.pk).delete()
            continue

        obj_to = attachment_to.objects.create(
            file=obj_from.file,
            md5=obj_from.md5,
            author=obj_from.author,
        )

        assert obj_from.pk == obj_to.pk


def forwards_func(apps, schema_editor):
    OldAttachment = apps.get_model('money', 'Attachment')
    NewAttachment = apps.get_model('system', 'Attachment')

    copy_attachments(OldAttachment, NewAttachment)


def reverse_func(apps, schema_editor):
    OldAttachment = apps.get_model('money', 'Attachment')
    NewAttachment = apps.get_model('system', 'Attachment')

    copy_attachments(NewAttachment, OldAttachment)


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_user_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID',
                )),
                ('file', models.FileField(
                    upload_to=system.models.Attachment.upload_to,
                )),
                ('md5', models.CharField(editable=False, max_length=36)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
