# Generated by Django 6.0.2 on 2026-02-07 04:02

import system.models
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Attachment = apps.get_model('system', 'Attachment')

    objs = Attachment.objects.all()

    for x in objs:
        x.digest = int(x.md5[:16], 16)

    Attachment.objects.bulk_update(objs, fields=['digest'])


def reverse_func(apps, schema_editor):
    Attachment = apps.get_model('system', 'Attachment')

    objs = Attachment.objects.all()

    for x in objs:
        x.md5 = format(x.digest, '016x')

    Attachment.objects.bulk_update(objs, fields=['md5'])


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_move_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='digest',
            field=system.models.Digest64Field(default=0),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='attachment',
            name='md5',
            field=models.CharField(default=0, max_length=36),
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='md5',
        ),
    ]
