# Generated by Django 6.0.4 on 2026-04-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_user_language_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
