# Generated by Django 6.0.4 on 2026-04-28 14:13

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    User = apps.get_model('system', 'user')

    User.objects.filter(is_active=True).update(is_verified=True)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_user_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(
                default=False,
                help_text='Designates whether this user is verified and authorized for using the system.',
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
