# Generated by Django 6.0.2 on 2026-04-28 23:00

import system.models
from django.db import migrations, models

GROUPS = [
    {
        'name': 'editors',
        'permissions': [
            'add_journal',
            'change_journal',
            'delete_journal',
            'view_journal',
        ],
        'users': {'is_active': True, 'is_superuser': True},
    },
    {
        'name': 'guests',
        'permissions': [
            'view_journal',
        ],
        'users': {'is_active': True, 'is_superuser': False},
    },
]


def forwards_func(apps, schema_editor):
    User = apps.get_model('system', 'user')
    Group = apps.get_model('auth', 'group')
    Permission = apps.get_model('auth', 'permission')

    for x in GROUPS:
        group, _created = Group.objects.get_or_create(name=x['name'])

        for p in x['permissions']:
            perm = Permission.objects.get(
                content_type__app_label='money',
                content_type__model='journal',
                codename=p,
            )
            group.permissions.add(perm)

        for x in User.objects.filter(**x['users']):
            x.groups.add(group)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_user_is_verified'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
