version: '3'

services:
  apache:
    build: ./extra/docker/apache
    container_name: n-apache
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - .:/opt/nomoney
    depends_on:
      - main

  postgresql:
    image: postgres:alpine
    container_name: n-postgresql
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: nmoney
      POSTGRES_USER: nmoney
      POSTGRES_PASSWORD: nmoney
    volumes:
      - ./extra/docker/postgresql/init:/docker-entrypoint-initdb.d
      - ./data/postgresql:/var/lib/postgresql/data

  main:
    build: .
    container_name: n-main
    volumes:
      - .:/opt/nomoney
    depends_on:
      - postgresql
    environment:
      N_ALLOWED_HOSTS: n-main
      N_DATABASE_ENGINE: django.db.backends.postgresql_psycopg2
      N_DATABASE_NAME: nmoney
      N_DATABASE_USER: nmoney
      N_DATABASE_PASSWORD: nmoney
      N_DATABASE_HOST: n-postgresql
      N_DATABASE_PORT: "5432"
      N_URL_PREFIX: /n
      N_STATIC_URL: /n/static/
      N_MEDIA_URL: /n/media/
