version: '3'

services:
  web:
    build:
      context: ./extra/docker/apache
    volumes:
      - .:/opt/app
    depends_on:
      - app
    environment:
      APP_PATH: /n/
      APP_STATIC_PATH: /n/static/
      APP_MEDIA_PATH: /n/media/
      APP_URL: http://app:49152/n/

  db:
    image: postgres:alpine
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: nmoney
      POSTGRES_USER: nmoney
      POSTGRES_PASSWORD: nmoney
    volumes:
      - ./_data/postgresql-init:/docker-entrypoint-initdb.d
      - ./_data/postgresql:/var/lib/postgresql/data

  app:
    build: .
    volumes:
      - .:/opt/nomoney
    environment:
      N_ALLOWED_HOSTS: app
      N_CSRF_TRUSTED_ORIGINS:
      N_DATABASE_HOST: db
      N_DATABASE_NAME: nmoney
      N_DATABASE_USER: nmoney
      N_DATABASE_PASSWORD: nmoney
      N_URL_PREFIX: /n
      N_STATIC_URL: /n/static/
      N_MEDIA_URL: /n/media/
      N_DEBUG: 'false'
