version: '3'

services:
  web:
    build:
      context: ./extra/docker/apache
    container_name: n-web
    ports:
      - "8000:80"
    volumes:
      - .:/opt/app
    depends_on:
      - app
    environment:
      APP_PATH: /n/
      APP_STATIC_PATH: /n/static/
      APP_MEDIA_PATH: /n/media/
      APP_URL: http://n-app:49152/h3/

  db:
    image: postgres:alpine
    container_name: n-db
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: nmoney
      POSTGRES_USER: nmoney
      POSTGRES_PASSWORD: nmoney
    volumes:
      - ./extra/docker/postgresql/init:/docker-entrypoint-initdb.d
      - ./data/postgresql:/var/lib/postgresql/data

  app:
    build: .
    container_name: n-app
    volumes:
      - .:/opt/nomoney
    depends_on:
      - db
    environment:
      N_ALLOWED_HOSTS: n-app
      N_DATABASE_ENGINE: django.db.backends.postgresql_psycopg2
      N_DATABASE_HOST: n-db
      N_DATABASE_PORT: "5432"
      N_DATABASE_NAME: nmoney
      N_DATABASE_USER: nmoney
      N_DATABASE_PASSWORD: nmoney
      N_URL_PREFIX: /n
      N_STATIC_URL: /n/static/
      N_MEDIA_URL: /n/media/
      N_DEBUG: 'false'
