version: '3'

services:
  web:
    build:
      context: ./extra/docker/apache
      args:
        N_URL_PREFIX: /n
        N_STATIC_URL: /n/static/
        N_MEDIA_URL: /n/media/
        N_URL_APP: http://n-app:49152/n
    container_name: n-web
    ports:
      - "8000:80"
    volumes:
      - .:/opt/nomoney
    depends_on:
      - app

  db:
    image: postgres:alpine
    container_name: n-db
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: nmoney
      POSTGRES_USER: nmoney
      POSTGRES_PASSWORD: nmoney
    volumes:
      - ./extra/docker/postgresql/init:/docker-entrypoint-initdb.d
      - ./data/postgresql:/var/lib/postgresql/data

  app:
    build: .
    container_name: n-app
    volumes:
      - .:/opt/nomoney
    depends_on:
      - db
    environment:
      N_ALLOWED_HOSTS: n-app
      N_DATABASE_ENGINE: django.db.backends.postgresql_psycopg2
      N_DATABASE_NAME: nmoney
      N_DATABASE_USER: nmoney
      N_DATABASE_PASSWORD: nmoney
      N_DATABASE_HOST: n-db
      N_DATABASE_PORT: "5432"
      N_URL_PREFIX: /n
      N_STATIC_URL: /n/static/
      N_MEDIA_URL: /n/media/
