# Generated by Django 5.1.1 on 2024-10-20 12:52

import doc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_page_previous_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='parent_slug',
            field=models.SlugField(choices=doc.models._slug_choices, default=None, null=True),
        ),
    ]
