# Copyright (C) Takeshi Nakamura. All rights reserved.

"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

# pylint: disable=line-too-long

import os
from pathlib import Path

import environ

from . import tinymce, version

env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('N_SECRET_KEY', default=None)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('N_DEBUG', default=False)

ALLOWED_HOSTS = env.list('N_ALLOWED_HOSTS', default=['localhost'])

CSRF_TRUSTED_ORIGINS = env.list('N_CSRF_TRUSTED_ORIGINS', default=[])

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.postgres.search',
    'django_filters',
    'fontawesomefree',
    'rest_framework',
    'user_g11n',
    'tinymce',
    'system',
    'doc',
    'money',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user_g11n.middleware.UserLanguageMiddleware',
    'user_g11n.middleware.UserTimeZoneMiddleware',
    'system.middleware.auth.AuthMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.context_processors.site_values',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': env('N_DATABASE_HOST', default=''),
        'PORT': env('N_DATABASE_PORT', default='5432'),
        'NAME': env('N_DATABASE_NAME', default=''),
        'USER': env('N_DATABASE_USER', default=''),
        'PASSWORD': env('N_DATABASE_PASSWORD', default=''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = env('N_LANGUAGE_CODE', default='en-us')

TIME_ZONE = env('N_TIME_ZONE', default='UTC')

USE_I18N = True

USE_L10N = True

USE_TZ = True

URL_PREFIX = env('N_URL_PREFIX', default='/n')

DOC_URL = f'{URL_PREFIX}/doc/'

ROUTE_PREFIX = URL_PREFIX[1:]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = env('N_STATIC_URL', default=f'{URL_PREFIX}/static/')

STATIC_ROOT = env(
    'N_STATIC_ROOT', default=os.path.join(BASE_DIR, 'staticfiles')
)

MEDIA_URL = env('N_MEDIA_URL', default=f'{URL_PREFIX}/media/')

MEDIA_ROOT = env('N_MEDIA_ROOT',  default=os.path.join(BASE_DIR, 'media'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'system.User'

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

LOGIN_URL = 'system:login'
LOGIN_REDIRECT_URL = 'money:home'
LOGOUT_URL = 'system:logout'
LOGOUT_REDIRECT_URL = 'system:login'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# Number of digits for filter initcomma
NUMBER_GROUPING = 3

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

FY_START_MONTH = 4
FY_START_DAY = 1

VERSION = version.VERSION

NAME = env('N_NAME', default='NoMoney')

TINYMCE_DEFAULT_CONFIG = tinymce.TINYMCE_DEFAULT_CONFIG
TINYMCE_DEFAULT_CONFIG.update({
    'content_css': [
        f'{STATIC_URL}vendor/bootstrap/css/bootstrap.min.css',
        f'{STATIC_URL}fontawesomefree/css/all.min.css',
        f'{STATIC_URL}doc/content.css',
    ],
    'image_list': f'{DOC_URL}__admin__/images',
    'link_list': f'{DOC_URL}__admin__/links',
    'file_picker_callback': '(c, v, m) => filePickerCallback(c, v, m)',
})

try:
    # pylint: disable=wildcard-import,unused-wildcard-import
    from .local_settings import *
except ImportError:
    pass

SITE_URL = f'{URL_PREFIX}/money/'
LOGIN_TARGETS = (f'{URL_PREFIX}/money/', )

if DEBUG:
    INSTALLED_APPS += ['debug_toolbar', ]
    MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware', ]
    DEBUG_TOOLBAR_CONFIG = {'SHOW_TOOLBAR_CALLBACK': lambda request: True}
