# Generated by Django 3.0.4 on 2020-04-04 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('entry', models.IntegerField(choices=[(1, 'Asset'), (2, 'Liability'), (3, 'Income'), (4, 'Expense'), (5, 'Equity')])),
                ('rank', models.IntegerField(default=0)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('summary', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('asset', models.IntegerField(blank=True, default=0)),
                ('liability', models.IntegerField(blank=True, default=0)),
                ('income', models.IntegerField(blank=True, default=0)),
                ('expense', models.IntegerField(blank=True, default=0)),
                ('equity', models.IntegerField(blank=True, default=0)),
                ('fy', models.IntegerField(blank=True, default=0, verbose_name='Financial year')),
                ('year', models.IntegerField(blank=True, default=0)),
                ('month', models.IntegerField(blank=True, default=0)),
                ('week', models.IntegerField(blank=True, default=0)),
                ('disabled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='journal_credit', to='money.Account')),
                ('debit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='journal_debit', to='money.Account')),
            ],
        ),
    ]
