# Generated by Django 4.0.4 on 2022-05-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_disabled2enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='month',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='week',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='year',
        ),
        migrations.AlterField(
            model_name='journal',
            name='asset',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='equity',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='expense',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='fy',
            field=models.IntegerField(blank=True, default=0, editable=False, verbose_name='Financial year'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='income',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='liability',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
