# Generated by Django 5.2.1 on 2025-06-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0009_template_tags'),
        ('system', '0007_move_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='system.attachment'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
