# Generated by Django 6.0.2 on 2026-02-15 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Journal = apps.get_model('money', 'Journal')

    objs = Journal.objects.all()

    for x in objs:
        x.payer = x.author

    Journal.objects.bulk_update(objs, fields=['payer'])


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0010_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='payer',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='journal_payer',
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
