# Generated by Django 6.0.2 on 2026-02-23 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0011_journal_payer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='payer',
            new_name='responsible',
        ),
        migrations.AlterField(
            model_name='journal',
            name='responsible',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='journal_responsible',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
