# Generated by Django 5.1.1 on 2024-10-05 06:55

import django.db.models.deletion
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Page = apps.get_model('doc', 'Page')
    fields = ('slug', 'language')
    field_set = Page.objects.values_list(*fields).order_by(*fields).distinct()

    for slug, lang in field_set:
        pages = Page.objects.filter(slug=slug, language=lang)
        prev = None

        for x in pages.order_by('updated'):
            x.previous_revision = prev
            x.save()
            prev = x


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_page_parent_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='previous_revision',
            field=models.ForeignKey(
                to='doc.page', blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
            ),
        ),
        # For reserving the timestamps.
        migrations.AlterField(
            model_name='page',
            name='updated',
            field=models.DateTimeField(),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='page',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
