# Generated by Django 5.2.8 on 2025-11-22 04:56

import doc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0005_page_parent_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='parent_slug',
            field=models.SlugField(blank=True, choices=doc.models._slug_choices, default=None, null=True),
        ),
    ]
