# Generated by Django 5.2.8 on 2025-11-19 12:00

from django.db import migrations, models

from doc.models import Page as NewPage


def forwards_func(apps, schema_editor):
    Page = apps.get_model('doc', 'Page')

    for x in Page.objects.all():
        if x.status == NewPage.Status.DRAFT:
            continue

        x.digest = NewPage.get_digest(x)
        x.save()


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0006_page_parent_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='digest',
            field=models.BigIntegerField(null=True),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='page',
            name='digest',
            field=models.BigIntegerField(default=True, null=True, unique=True),
        ),
    ]
