# Generated by Django 5.2.8 on 2025-11-19 12:00

import django.db.models.deletion
from django.db import migrations, models

from doc.models import Page as NewPage


def forwards_func(apps, schema_editor):
    Page = apps.get_model('doc', 'Page')

    for x in Page.objects.all():
        x.previous_revision = x.old_previous_revision
        x.save()


def reverse_func(apps, schema_editor):
    Page = apps.get_model('doc', 'Page')

    for x in Page.objects.all():
        x.old_previous_revision = x.previous_revision
        x.save()


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0007_page_digest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='previous_revision',
            new_name='old_previous_revision',
        ),
        migrations.AddField(
            model_name='page',
            name='previous_revision',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='doc.page', to_field='digest',
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name='page',
            name='old_previous_revision',
        ),
    ]
