# Generated by Django 5.2.8 on 2025-11-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0008_page_digest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='digest',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
