# Generated by Django 6.0 on 2026-01-27 15:49

import system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0009_page_digest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='digest',
            field=system.models.Digest64Field(null=True, unique=True),
        ),
    ]
