# Generated by Django 6.0.5 on 2026-05-24 08:29

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0012_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Celler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('lwin', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Live', 'active'), ('Combined', 'Combined'), ('Deleted', 'Deleted')], max_length=16)),
                ('display_name', models.CharField(max_length=256)),
                ('producer_title', models.CharField(blank=True, max_length=64)),
                ('producer_name', models.CharField(blank=True, max_length=128)),
                ('wine', models.CharField(blank=True, max_length=256)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('sub_region', models.CharField(blank=True, max_length=64)),
                ('site', models.CharField(blank=True, max_length=64)),
                ('parcel', models.CharField(blank=True, max_length=32)),
                ('colour', models.CharField(blank=True, choices=[('Red', 'Red'), ('White', 'White'), ('Rose', 'Rose'), ('Mixed', 'Mixed')], max_length=16)),
                ('type', models.CharField(choices=[('Wine', 'Wine'), ('Beer', 'Beer'), ('Cider', 'Cider'), ('Fortified Wine', 'Fortified wine'), ('Other', 'Other'), ('Spirit', 'Spirit'), ('Still', 'Still')], max_length=16)),
                ('sub_type', models.CharField(blank=True, choices=[('Absinthe', 'Absinthe'), ('Aquavit', 'Aquavit'), ('Bitters', 'Bitters'), ('Brandy', 'Brandy'), ('Cachaca', 'Cachaca'), ('Genever', 'Genever'), ('Gin', 'Gin'), ('Liqueur', 'Liqueur'), ('Madeira', 'Madeira'), ('Marsala', 'Marsala'), ('Mezcal', 'Mezcal'), ('Montilla-Moriles', 'Montilla-Moriles'), ('Moscatel de Setubal', 'Moscatel de Setubal'), ('Port', 'Port'), ('Rum', 'Rum'), ('Rutherglen', 'Rutherglen'), ('Sake', 'Sake'), ('Sherry', 'Sherry'), ('Shochu', 'Shochu'), ('Sparkling', 'Sparkling'), ('Still', 'Still'), ('Tequila', 'Tequila'), ('Vermouth', 'Vermouth'), ('Vin Doux Naturel', 'Vin Doux Naturel'), ('Vodka', 'Vodka'), ('Whiskies', 'Whiskies')], max_length=32)),
                ('designation', models.CharField(blank=True, max_length=32)),
                ('classification', models.CharField(blank=True, max_length=32)),
                ('vintage_config', models.CharField(max_length=20)),
                ('first_vintage', models.IntegerField()),
                ('final_vintage', models.IntegerField()),
                ('date_added', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vintage', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('acquired', models.DateTimeField()),
                ('price', models.IntegerField(default=0)),
                ('shop', models.CharField(blank=True, max_length=256)),
                ('uncorked', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('images', models.ManyToManyField(blank=True, to='system.attachment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('celler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wine.celler')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wine.wine')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
