# Generated by Django 6.0.6 on 2026-06-27 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0012_journal_responsible'),
        ('wine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='money.journal'),
        ),
    ]
